services:
  backend:
    build:
      context: ./backend

    container_name: receipt_backend
    restart: unless-stopped

    environment:
      DATABASE_URL: ${DATABASE_URL}

      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL_NAME: ${GEMINI_MODEL_NAME}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_EXPIRE_MINUTES: ${JWT_EXPIRE_MINUTES}

      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_FULL_NAME: ${ADMIN_FULL_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      EMPLOYEE_USERNAME: ${EMPLOYEE_USERNAME}
      EMPLOYEE_FULL_NAME: ${EMPLOYEE_FULL_NAME}
      EMPLOYEE_PASSWORD: ${EMPLOYEE_PASSWORD}

    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend

    container_name: receipt_frontend
    restart: unless-stopped

    environment:
      API_BASE_URL: ${API_BASE_URL}

    ports:
      - "8501:8501"

    depends_on:
      - backend